# This file has been auto-generated by cookiecutter. Update or delete it.

from rcmt import Context, Task, register_task


class Example(Task):
    name = "example"

    def filter(self, ctx: Context) -> bool:
        # Add filter criteria here
        return False

    def apply(self, ctx: Context) -> None:
        # Make modifications here
        pass


register_task(Example())
