# This file has been auto-generated by cookiecutter. Update or delete it.

from rcmt import Context, Task, register_task


class Example(Task):
    name = "example"

    def filter(self, ctx: Context) -> bool:
        # Add filter criteria here
        return ctx.repo.full_name == "example.dev/local/test"

    def apply(self, ctx: Context) -> None:
        # Make modifications here
        with open("example.txt", "w+") as f:
            f.write("example\n")


register_task(Example())
