[project]
name = "{{ cookiecutter.project_slug }}"
requires-python = ">=3.9"
dependencies = [
  "rcmt=={{ cookiecutter._rcmt_version }}"
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
  "pytest>=7.4.3"
]

[tool.setuptools]
packages = ["{{ cookiecutter.package_name }}"]
