name: Pull Request

on:
  pull_request: {}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.12"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: make test
